CREATE TABLE [dbo].[ROUTE_TEMPLATE](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[NAME] [varchar](500) NOT NULL,
	[ROUTE_ID] [int] NOT NULL,
	[SYSTEM_ID] [int] NOT NULL,
	[CUSTOMER_ID] [int] NOT NULL,
	[CREATED_BY] [varchar](500) NOT NULL,
	[CREATED_DATE] [datetime] NOT NULL,
	[UPDATED_BY] [varchar](500) NULL,
	[UPDATED_DATE] [datetime] NULL,
	[TRIP_CUST_ID] [int] NULL
) ON [PRIMARY]

CREATE TABLE [dbo].[ROUTE_LEG_MATERIAL_ASSOC](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[TEMPLATE_ID] [int] NOT NULL,
	[MATERIAL_ID] [int] NOT NULL,
	[LEG_ID] [int] NOT NULL,
	[TAT] [numeric](18, 2) NOT NULL,
	[RUN_TIME] [numeric](18, 2) NOT NULL,
	[DETENTION] [numeric](18, 2) NOT NULL,
	[SYSTEM_ID] [int] NOT NULL,
	[CUSTOMER_ID] [int] NOT NULL,
	[TRIP_CUST_ID] [int] NULL
) ON [PRIMARY]

ALTER TABLE ROUTE_LEG_MATERIAL_ASSOC ADD [IS_DELETED] [varchar](3) NULL

ALTER TABLE AMS.dbo.TRIP_SHEET_SETTING ADD MATERIAL_CLIENT [varchar](50) NULL

ALTER TABLE TRACK_TRIP_DETAILS ADD MATERIAL_ID [int] NULL

ALTER TABLE TRACK_TRIP_DETAILS ADD ROUTE_TEMPLATE_ID [int] NULL

