CREATE TABLE [dbo].[LIST_VIEW_COLUMN_SETTING](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[PAGE_NAME] [varchar](500) NOT NULL,
	[COLUMN_NAME] [varchar](500) NOT NULL,
	[VISIBILITY] [int] NOT NULL,
	[SYSTEM_ID] [int] NOT NULL,
	[CUSTOMER_ID] [int] NOT NULL,
	[USER_ID] [int] NOT NULL,
) 