package t4u.statements;

public class AccidentAnalysisStatements {
	
	public final String GET_ACCIDENT_LOOKUP_MASTER = "select ID,TYPE,VALUE from ACCIDENT_LOOKUP_DETAILS where TYPE = ?";

	public final String GET_CASE_ID_TO_INCREMENT = "select top 1 CASE_ID from dbo.ACCIDENT_CASE_INFO where SYSTEM_ID = ? and CUSTOMER_ID = ? order by CASE_ID desc";
	
	public final String SAVE_ACCIDENT_CASE_INFORMATION = "INSERT INTO [AMS].[dbo].[ACCIDENT_CASE_INFO] ([CASE_ID],[CASE_NUMBER],[ASSET_NUMBER],[DRIVER_ID],[ACCIDENTAL_TYPE],[COLLATED_WITH],[SECONDARY_ASSET_NUMBER],[SECONDARY_DRIVER_NAME],[OTHER_DETAILS],[ACCIDENT_LOCATION],[ACCIDENT_DATE],[LOSS_OF_LIFE],[INJURED],[INSURANCE_AMOUNT],[FAULTY_ASSET],[SETTELMENT],[CASE_STATUS],[SYSTEM_ID],[CUSTOMER_ID],[CREATED_BY]) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)";

	public final String UPDATE_ACCIDENT_CASE_INFORMATION = "update dbo.ACCIDENT_CASE_INFO set DRIVER_ID = ? , ACCIDENTAL_TYPE = ?, COLLATED_WITH = ?, SECONDARY_ASSET_NUMBER = ?,SECONDARY_DRIVER_NAME = ?,OTHER_DETAILS = ?, ACCIDENT_LOCATION = ?, ACCIDENT_DATE = ?, LOSS_OF_LIFE = ?, INJURED = ?, INSURANCE_AMOUNT = ?, FAULTY_ASSET = ?, SETTELMENT = ?, CASE_STATUS = ?, MODIFIED_BY = ? ,MODIFIED_TIME = getUTCDate() where SYSTEM_ID = ? and CUSTOMER_ID = ? and ASSET_NUMBER = ? and CASE_NUMBER = ? and  CASE_ID = ?";
	
	public final String GET_CASE_INFORMATION_DETAILS = "select a.CASE_ID,isNull(a.CASE_NUMBER,'') as CASE_NUMBER,isNull(a.ASSET_NUMBER,'') as ASSET_NUMBER," +
			"a.DRIVER_ID,isNull(b.Fullname,'') as DRIVER_NAME,a.ACCIDENTAL_TYPE as ACCIDENTAL_TYPE_ID,isNull(c.VALUE,'') as ACCIDENTAL_TYPE," +
			"a.COLLATED_WITH as COLLATED_WITH_ID,isNull(d.VALUE,'') as COLLATED_WITH,isNull(a.SECONDARY_ASSET_NUMBER,'') as SECONDARY_ASSET_NUMBER," +
			"isNull(a.SECONDARY_DRIVER_NAME,'') as SECONDARY_DRIVER_NAME,isNull(a.OTHER_DETAILS,'') as OTHER_DETAILS," +
			"isNull(a.ACCIDENT_LOCATION,'') as ACCIDENT_LOCATION,a.ACCIDENT_DATE,a.LOSS_OF_LIFE,a.INJURED," +
			"isNull(a.INSURANCE_AMOUNT,0) as INSURANCE_AMOUNT,a.FAULTY_ASSET,a.SETTELMENT as SETTELMENT_ID,isNull(e.VALUE,'') as SETTELMENT," +
			"a.CASE_STATUS as CASE_STATUS_ID,isNull(f.VALUE,'') as CASE_STATUS,a.SYSTEM_ID,a.CUSTOMER_ID,a.CREATED_BY from dbo.ACCIDENT_CASE_INFO a " +
			"left outer join dbo.Driver_Master b on a.DRIVER_ID = b.Driver_id and a.SYSTEM_ID = b.System_id and a.CUSTOMER_ID = b.Client_id " +
			"left outer join dbo.ACCIDENT_LOOKUP_DETAILS c on a.ACCIDENTAL_TYPE = c.ID " +
			"left outer join dbo.ACCIDENT_LOOKUP_DETAILS d on a.COLLATED_WITH = d.ID " +
			"left outer join dbo.ACCIDENT_LOOKUP_DETAILS e on a.SETTELMENT = e.ID " +
			"left outer join dbo.ACCIDENT_LOOKUP_DETAILS f on a.CASE_STATUS = f.ID " +
			"where f.VALUE = 'Open' and a.SYSTEM_ID = ? and a.CUSTOMER_ID = ?";
	
	public final String GET_CASE_NUMBER = "select CASE_ID,CASE_NUMBER from dbo.ACCIDENT_CASE_INFO where SYSTEM_ID = ? and CUSTOMER_ID = ? and CASE_STATUS != 9 order by CASE_NUMBER";

	public final String GET_COMPENSATION_ID_TO_INCREMENT = "select top 1 COMPENSATION_ID from dbo.ACCIDENT_COMPENSATION_INFO where CASE_ID = ? and CUSTOMER_ID = ? order by COMPENSATION_ID desc";
	
	public final String SAVE_ACCIDENT_COMPENSATION_INFORMATION = "INSERT INTO [AMS].[dbo].[ACCIDENT_COMPENSATION_INFO] ([COMPENSATION_ID],[CASE_ID],[REFERENCE_NUMBER],[COMPENSATION_TYPE],[MODE_OF_TRANSACTION],[TRANSACTION_TYPE],[TRANSACTION_DATE],[TRANSACTION_AMOUNT],[TRANSACTION_NUMBER] ,[COMPENSATION_PAID_IN], [COMPENSATION_PAID_OUT], [INTERNAL_EXPENSES], [NEXT_HEARING_DATE],[CUSTOMER_ID],[CREATED_BY]) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)";
	
	public final String UPDATE_ACCIDENT_COMPENSATION_INFORMATION = "update dbo.ACCIDENT_COMPENSATION_INFO set REFERENCE_NUMBER =?, COMPENSATION_TYPE = ?, MODE_OF_TRANSACTION = ? , TRANSACTION_TYPE = ?, TRANSACTION_DATE= ?, TRANSACTION_AMOUNT = ?, TRANSACTION_NUMBER = ?, COMPENSATION_PAID_IN=?, COMPENSATION_PAID_OUT = ?, INTERNAL_EXPENSES = ?,  NEXT_HEARING_DATE = ?, MODIFIED_BY = ? , MODIFIED_TIME = getUTCDate() where COMPENSATION_ID = ? and CASE_ID = ? and CUSTOMER_ID = ?";
	
	public final String GET_COMPENSATION_INFORMATION_DETAILS = "select a.COMPENSATION_ID,b.CASE_NUMBER,b.ASSET_NUMBER,a.REFERENCE_NUMBER,a.COMPENSATION_TYPE as COMPENSATION_TYPE_ID,isNull(c.VALUE,'') as COMPENSATION_TYPE," +
			"a.MODE_OF_TRANSACTION as MODE_OF_TRANSACTION_ID,isNull(d.VALUE,'') as MODE_OF_TRANSACTION,a.TRANSACTION_TYPE as TRANSACTION_TYPE_ID,isNull(e.VALUE,'') as TRANSACTION_TYPE," +
			"a.TRANSACTION_DATE,a.TRANSACTION_AMOUNT,isNull(a.TRANSACTION_NUMBER,'') as TRANSACTION_NUMBER," +
			"a.COMPENSATION_PAID_IN,a.COMPENSATION_PAID_OUT,a.INTERNAL_EXPENSES,isNull(a.NEXT_HEARING_DATE,'') as NEXT_HEARING_DATE " +
			"from dbo.ACCIDENT_COMPENSATION_INFO a " +
			"left outer join dbo.ACCIDENT_CASE_INFO b on a.CASE_ID = b.CASE_ID and a.CUSTOMER_ID = b.CUSTOMER_ID " +
			"left outer join dbo.ACCIDENT_LOOKUP_DETAILS c on c.ID = a.COMPENSATION_TYPE " +
			"left outer join dbo.ACCIDENT_LOOKUP_DETAILS d on d.ID = a.MODE_OF_TRANSACTION " +
			"left outer join dbo.ACCIDENT_LOOKUP_DETAILS e on e.ID = a.TRANSACTION_TYPE " +
			"where a.CUSTOMER_ID = ? and a.CASE_ID = ?";
	
	public final String GET_ACCIDENT_EXPENDITURE_SUMMARY = "select temp.ASSET_NUMBER,temp.PAYMENT,temp.RECEIPT,count(c.ASSET_NUMBER) as NO_OF_ACCIDENTS,sum(c.LOSS_OF_LIFE) as TOTAL_LOSS_OF_LIFE,sum(c.INJURED) as TOTAL_INJURED," +
			"sum(case when c.CASE_STATUS = 8 then 1 else 0 end) as TOTAL_CASES_OPENED," +
			"sum(case when c.CASE_STATUS = 9 then 1 else 0 end) as TOTAL_CASES_CLOSED from " +
			"(select a.ASSET_NUMBER,a.CUSTOMER_ID,sum(case when b.COMPENSATION_TYPE = 10 then b.TRANSACTION_AMOUNT else 0 end) as PAYMENT," +
			"sum(case when b.COMPENSATION_TYPE = 11 then b.TRANSACTION_AMOUNT else 0 end) as RECEIPT " +
			"from dbo.ACCIDENT_CASE_INFO a " +
			"left outer join dbo.ACCIDENT_COMPENSATION_INFO b on a.CASE_ID = b.CASE_ID and a.CUSTOMER_ID = b.CUSTOMER_ID " +
			"where a.SYSTEM_ID = ? and a.CUSTOMER_ID = ? group by a.CUSTOMER_ID,a.ASSET_NUMBER) temp " +
			"inner join dbo.ACCIDENT_CASE_INFO c on temp.ASSET_NUMBER = c.ASSET_NUMBER and temp.CUSTOMER_ID = c.CUSTOMER_ID " +
			"group by temp.CUSTOMER_ID,c.CUSTOMER_ID,temp.ASSET_NUMBER,c.ASSET_NUMBER,temp.PAYMENT,temp.RECEIPT";

	public final String GET_ACCIDENT_ASSET_NUMBER = "select distinct ASSET_NUMBER from ACCIDENT_CASE_INFO where SYSTEM_ID = ? and CUSTOMER_ID = ? order by ASSET_NUMBER";

	public final String GET_ACCIDENT_EXPENDITURE_DETAILS = "select a.CASE_ID,a.CASE_NUMBER,a.ASSET_NUMBER,isNull(b.Fullname,'')  as DRIVER_NAME,isNull(c.VALUE,'') as ACCIDENTAL_TYPE,isnull(a.ACCIDENT_DATE,'') as ACCIDENT_DATE,isNull(a.ACCIDENT_LOCATION,'') as ACCIDENT_LOCATION,isNull(a.INSURANCE_AMOUNT,0) as INSURANCE_AMOUNT,isNull(a.LOSS_OF_LIFE,0) as LOSS_OF_LIFE,isNull(a.INJURED,0) as INJURED, isNull(d.VALUE,'') as CASE_STATUS from dbo.ACCIDENT_CASE_INFO a " +
			"left outer join Driver_Master b on a.DRIVER_ID = b.Driver_id and a.SYSTEM_ID = b.System_id and a.CUSTOMER_ID = b.Client_id " +
			"left outer join dbo.ACCIDENT_LOOKUP_DETAILS c on a.ACCIDENTAL_TYPE = c.ID " +
			"left outer join dbo.ACCIDENT_LOOKUP_DETAILS d on a.CASE_STATUS = d.ID " +
			"where a.ASSET_NUMBER = ? and a.SYSTEM_ID = ? and a.CUSTOMER_ID = ?";

	public final String GET_AMOUNT_BASED_ON_TRANSACTION_TYPE = "select COMPENSATION_TYPE,sum(TRANSACTION_AMOUNT) as TRANSACTION_AMOUNT from ACCIDENT_COMPENSATION_INFO where CASE_ID  = ? and CUSTOMER_ID = ? group by COMPENSATION_TYPE";

}
