package t4u.statements;

public class ReportBuilderStatements {

	public static final String GET_USER_VEHICLE = "select REGISTRATION_NUMBER from VEHICLE_CLIENT vc"+
	" inner join Vehicle_User vu on vu.Registration_no=vc.REGISTRATION_NUMBER and vu.System_id=vc.SYSTEM_ID and vu.User_id=?"+
	" where vc.SYSTEM_ID=? and vc.CLIENT_ID=?";
	
	public static final String GET_TRIP_NAMES = "select td.ASSET_NUMBER,td.TRIP_ID,(td.ORDER_ID+'-('+td.SHIPMENT_ID+')-'+td.ASSET_NUMBER) as SHIPMENT_ID,td.ACTUAL_TRIP_START_TIME as START_DATE,"+
	" (case when de.ACT_ARR_DATETIME is null then getutcdate() else de.ACT_ARR_DATETIME end) as END_DATE from TRACK_TRIP_DETAILS td"+
	" left outer join DES_TRIP_DETAILS de on de.TRIP_ID=td.TRIP_ID and de.SEQUENCE=100"+
	" where SYSTEM_ID=? and CUSTOMER_ID=? and td.ACTUAL_TRIP_START_TIME is not null";

	public static final String GET_REPORT_MASTER = "select REPORT_ID,REPORT_NAME,isnull(SINGLE_OR_MULTIPLE,'') as singleMulti,isnull(SELECTION_TYPE,'Vehicle') as SELECTION_TYPE,isnull(EXTRA_INPUT_FIELDS,'') as EXTRA_INPUT_FIELDS,isnull(REPORT_INFO,'') as REPORT_INFO from REPORT_MASTER " +
	" where CATEGORY_ID = ? and STATUS='Active' # order by DISPLAY_ORDER";

	public static final String GET_REPORT_CATEGORIES = "select CATEGORY_ID,CATEGORY_NAME from REPORT_MASTER group by CATEGORY_ID,CATEGORY_NAME";

	public static final String GET_PARAMETERS = "select PARAMETER_ID,PARAMETER_ALIAS from dbo.REPORT_PARAMETERS where REPORT_ID=?";

	public static final String GET_SQL_QUERY = "select SQL_QUERY from dbo.REPORT_PARAMETERS where REPORT_ID=? and PARAMETER_ID=? and SQL_QUERY != ''" +
	" and SQL_QUERY is not null";

	public static final String GET_COLUMN_DESC = "select COLUMN_NAME,FILTER,FILTER_TYPE from dbo.REPORT_COLUMN_MASTER where UPPER(PARAMETER)=?";

	public static final String GET_HUB_NAMES = " select NAME,HUBID from LOCATION_ZONE_# where SYSTEMID=? and CLIENTID=? and OPERATION_ID in (32,33)";
	
	public static final String GET_TRIP_DETAILS_FOR_GIVEN_TRIP_IDS = "SELECT ASSET_NUMBER,TRIP_ID,STATUS,SHIPMENT_ID,ACTUAL_TRIP_START_TIME,isnull(ACTUAL_TRIP_END_TIME,getutcdate()) as ACTUAL_TRIP_END_TIME FROM TRACK_TRIP_DETAILS where  SYSTEM_ID = ?  AND CUSTOMER_ID = ?  AND TRIP_ID = ?";
	
	public static final String GET_VEHICLE_TYPES = "select distinct VehicleType from tblVehicleMaster where System_id=?";
	
	public static final String GET_LAST_AND_NEW_TRIP_FOR_VEHICLE = "SELECT pass1.* FROM (SELECT STATUS,ASSET_NUMBER,SHIPMENT_ID,ORDER_ID,dateadd(mi, ?,ACTUAL_TRIP_END_TIME) as ACTUAL_TRIP_END_TIME,dateadd(mi, ?,INSERTED_TIME) as INSERTED_TIME, isnull(CUSTOMER_NAME,'NA') as CUSTOMER_NAME, "+ 
								" (SELECT TOP (1)  LOCATION FROM HISTORY_DATA_268 WHERE REGISTRATION_NO=? AND GMT BETWEEN DATEADD(mi,-10,td1.INSERTED_TIME) and "+ 
								" DATEADD(mi,10,td1.INSERTED_TIME) union SELECT TOP (1) LOCATION FROM AMS_Archieve.dbo.GE_DATA_268 WHERE REGISTRATION_NO=? AND "+
								" GMT BETWEEN DATEADD(mi,-10,td1.INSERTED_TIME) and "+
								" DATEADD(mi,10,td1.INSERTED_TIME)) AS LOCATION,DATEADD(mi,?,ACT_SRC_ARR_DATETIME) as ACT_SRC_ARR_DATETIME FROM "+
								" TRACK_TRIP_DETAILS td1 WHERE ASSET_NUMBER=? AND STATUS='OPEN' ) pass1"+
								" UNION ALL"+
								" SELECT pass2.* FROM (SELECT TOP(1) STATUS,ASSET_NUMBER,SHIPMENT_ID,ORDER_ID,dateadd(mi, ?,ACTUAL_TRIP_END_TIME) as ACTUAL_TRIP_END_TIME ,dateadd(mi, ?,INSERTED_TIME) as INSERTED_TIME, isnull(CUSTOMER_NAME,'NA') as CUSTOMER_NAME,  "+
								" (SELECT TOP (1)  LOCATION FROM HISTORY_DATA_268 WHERE REGISTRATION_NO=? AND GMT BETWEEN DATEADD(mi,-10,td2.ACTUAL_TRIP_END_TIME) and "+ 
								" DATEADD(mi,10,td2.ACTUAL_TRIP_END_TIME) union SELECT TOP (1)  LOCATION" +
								" FROM AMS_Archieve.dbo.GE_DATA_268 WHERE REGISTRATION_NO=? " +
								" AND GMT BETWEEN DATEADD(mi,-10,td2.ACTUAL_TRIP_END_TIME) and "+ 
								" DATEADD(mi,10,td2.ACTUAL_TRIP_END_TIME)) AS LOCATION, DATEADD(mi,?,ACT_SRC_ARR_DATETIME) as ACT_SRC_ARR_DATETIME "+
								" FROM TRACK_TRIP_DETAILS td2 WHERE ASSET_NUMBER=? AND STATUS='CLOSED' AND ACTUAL_TRIP_END_TIME between dateadd(mi,-?,?) and dateadd(mi,-?,?) "+
								" ORDER BY ACTUAL_TRIP_END_TIME DESC)AS pass2 ORDER BY STATUS";

	public static final String GET_BASE_QUERY = "SELECT BASE_QUERY FROM REPORT_CATEGORY_MASTER WHERE CATEGORY_ID=? ";// AND SYSTEM_ID=? AND CUSTOMER_ID=?";
	
	public static final String GET_SELECT_PARAMS = "SELECT SELECT_PARAM FROM REPORT_MASTER WHERE REPORT_ID IN (#)";
	
	public static final String GET_GROUP_BY_PARAMS = "SELECT PARAMETER_ID,PARAMETER_QUERY FROM REPORT_CATEGORY_PARAMETER_ASSOC WHERE CATEGORY_ID=? AND PARAMETER_ID IN (#) ORDER BY DISPLAY_ORDER";
	
}
 	