package t4u.statements;

public class RouteMasterStatements {
	
	public static final String GET_VEHICLE_TYPE = " SELECT DISTINCT a.VehicleType FROM tblVehicleMaster a "+
												  " INNER JOIN AMS.dbo.VEHICLE_CLIENT b ON a.System_id=b.SYSTEM_ID AND a.VehicleNo=b.REGISTRATION_NUMBER "+
												  " WHERE a.System_id=? AND b.CLIENT_ID=? ORDER BY a.VehicleType ";
	
	public static final String GET_SOURCE_DESTINATION_AND_CHECK_POINTS = " SELECT HUBID,NAME FROM AMS.dbo.LOCATION_ZONE WHERE OPERATION_ID NOT IN(2,13) AND CLIENTID=? AND SYSTEMID=? ";
	
	public static final String GET_ROUTE_MASTER_DETAILS = " SELECT a.ROUTE_ID,a.VEHICLE_TYPE,a.TRIP_CODE,a.TRIP_NAME,a.DESTINATION_DEPARTURE,a.DISTANCE,a.ORIGIN,b.NAME AS SOURCE,a.DESTINATION,c.NAME AS DESTINATIONNAME,isnull(e.GROUP_NAME,'ALL') as GROUP_NAME,a.GROUP_ID, "+
														  " COUNT(d.ROUTE_ID) as NOOFCHECKPOINT FROM  AMS.dbo.ROUTE_SKELETON a "+ 
														  " LEFT OUTER JOIN AMS.dbo.LOCATION_ZONE_# b ON a.ORIGIN=b.HUBID AND a.SYSTEM_ID=b.SYSTEMID AND a.CUSTOMER_ID=b.CLIENTID "+ 
														  " LEFT OUTER JOIN AMS.dbo.LOCATION_ZONE_# c ON a.DESTINATION=c.HUBID AND a.SYSTEM_ID=c.SYSTEMID AND a.CUSTOMER_ID=c.CLIENTID "+ 
														  " LEFT OUTER JOIN AMS.dbo.ROUTE_TRANSITION_POINTS d ON d.CUSTOMER_ID=a.CUSTOMER_ID AND a.SYSTEM_ID=d.SYSTEM_ID AND a.ROUTE_ID=d.ROUTE_ID "+
														  " LEFT OUTER JOIN ADMINISTRATOR.dbo.ASSET_GROUP e ON a.GROUP_ID=e.GROUP_ID and e.CUSTOMER_ID=a.CUSTOMER_ID AND e.SYSTEM_ID=a.SYSTEM_ID"+
														  " WHERE a.SYSTEM_ID=? AND a.CUSTOMER_ID=? AND a.TYPE=? "+ 
														  " GROUP BY d.ROUTE_ID,a.VEHICLE_TYPE,a.TRIP_CODE,a.TRIP_NAME,a.DESTINATION_DEPARTURE,a.ORIGIN,b.NAME,a.DESTINATION,c.NAME,a.ROUTE_ID,a.DISTANCE,a.GROUP_ID,e.GROUP_NAME ORDER By a.ROUTE_ID desc";
	
	public static final String SAVE_ROUTE_MASTER_DETAILS = " INSERT INTO AMS.dbo.ROUTE_SKELETON(TRIP_NAME,TRIP_CODE,ORIGIN,DESTINATION,DESTINATION_DEPARTURE,DISTANCE,VEHICLE_TYPE, "+
														   " SYSTEM_ID,CUSTOMER_ID,CREATED_BY,CREATED_TIME,TYPE,GROUP_ID) VALUES(?,?,?,?,?,?,?,?,?,?,GETUTCDATE(),?,?) ";
	
	public static final String SAVE_CHECK_POINT = " INSERT INTO AMS.dbo.ROUTE_TRANSITION_POINTS(ROUTE_ID,TRANSITION_POINT,TRANSITION_POINT_ARRIVAL,SEQUENCE,CUSTOMER_ID,SYSTEM_ID) VALUES(?,?,?,?,?,?) ";

	public static final String UPDATE_ROUTE_MASTER = " UPDATE AMS.dbo.ROUTE_SKELETON SET TRIP_NAME=?,TRIP_CODE=?,ORIGIN=?,DESTINATION=?,DESTINATION_DEPARTURE=?, "+
													 " DISTANCE=?,VEHICLE_TYPE=?,GROUP_ID=? WHERE SYSTEM_ID=? AND CUSTOMER_ID=? AND TYPE=? AND ROUTE_ID=? ";
	
	public static final String DELETE_CHECK_POINT = " DELETE FROM AMS.dbo.ROUTE_TRANSITION_POINTS WHERE SYSTEM_ID=? AND CUSTOMER_ID=? AND ROUTE_ID=? ";
	
	public static final String GET_CHECKPOINTS = " SELECT TRANSITION_POINT,TRANSITION_POINT_ARRIVAL,SEQUENCE FROM AMS.dbo.ROUTE_TRANSITION_POINTS "+
												 " WHERE SYSTEM_ID=? AND CUSTOMER_ID=? AND ROUTE_ID=? "; 
	
	public static final String SELECT_GROUP_LIST ="select a.GROUP_ID,a.GROUP_NAME from ADMINISTRATOR.dbo.ASSET_GROUP a "
		+ " inner join ADMINISTRATOR.dbo.USER_ASSET_GROUP_ASSOCIATION b on b.SYSTEM_ID=a.SYSTEM_ID and b.GROUP_ID=a.GROUP_ID " 
		+ " where a.SYSTEM_ID=?  and a.CUSTOMER_ID=? and b.USER_ID=? ";
}
